In [3]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from word2number import w2n

In [4]:
df = pd.read_csv('hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [5]:
df.experience = df.experience.fillna('Two')

df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        Two                    8.0                           9      50000
1        Two                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [6]:
import math
median_test_score = math.floor(df['test_score(out of 10)'].mean())
median_test_score

7

In [8]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(median_test_score)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        Two                    8.0                           9      50000
1        Two                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    7.0                           7      72000
7     eleven                    7.0                           8      80000

In [9]:
df.experience = df.experience.apply(w2n.word_to_num)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           2                    8.0                           9      50000
1           2                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [11]:
REG = linear_model.LinearRegression()
REG.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)',]] , df['salary($)'])

LinearRegression()

In [12]:
REG.predict([[2,9,6]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([49789.59159478])

In [13]:
REG.predict([[12,10,10]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([96804.05543518])

In [14]:
REG.score(df[['experience','test_score(out of 10)','interview_score(out of 10)',]],df['salary($)'])

0.9054602455727339

### Save Model To a File Using Python Pickle

In [15]:
# .pickle extension model , h5. or .json,  games or programs.exe
import pickle

In [16]:
with open('model_pickle','wb') as file:   # write binary
    pickle.dump(REG,file)                 # put model into file

### Load Saved Model

In [17]:
with open('model_pickle','rb') as file:
    mp = pickle.load(file)        # model is loaded into : ourModel

In [18]:
mp.coef_

array([3373.05915539, 2314.96668166, 2742.22640121])

In [19]:
mp.intercept_

5755.414741833913

In [21]:
mp.score(df[['experience','test_score(out of 10)','interview_score(out of 10)',]],df['salary($)'])

0.9054602455727339

In [22]:
## function for save model

def save_model(model,modelname):
    with open(modelname,'wb') as file:
        pickle.dump(model,file)

In [23]:
save_model(REG,'model_pickle')

### Save Trained Model Using joblib

In [25]:
import joblib

In [26]:
joblib.dump(REG,'model_joblib')

['model_joblib']

In [28]:
def savemodel(model, modelname):
    import joblib
    joblib.dump(model, modelname)
    print("Done, model saved.")

In [29]:
savemodel(REG,'model_joblib')

Done, model saved.


### Load Saved Model

In [30]:
mj = joblib.load('model_joblib')

In [31]:
mj.coef_

array([3373.05915539, 2314.96668166, 2742.22640121])

In [32]:
mj.intercept_

5755.414741833913

In [36]:
mj.score(df[['experience','test_score(out of 10)','interview_score(out of 10)',]],df['salary($)'])

0.9054602455727339